config/routes.rb
Rails.application.routes.draw do

  get 'users/search', to: 'users#search', as: 'search_users'
  get 'teams/search', to: 'teams#search', as: 'search_teams'
  
  root :controller => 'homepages', :action => "index", :as => :home

  resources :teams, :only => [:new, :create, :edit, :update, :index, :show, :destroy] do
    resources :people, :only => [:new, :create, :edit, :update, :destroy]
    resource :questions, :only => [:show, :create]
  end

  resources :races, :only => [:new, :create, :edit, :update, :index, :show, :destroy] do
    get :registrations
    get :export
    resources :requirements, :only => [:new, :create, :edit, :update, :destroy]
  end

  resources :tiers, :only => [:new, :create, :edit, :update, :destroy]

  resources :charges, :only => [:create] do
    post :refund
  end

  resources :users, :only => [:new, :create, :edit, :update, :index, :show, :destroy]
  resource :user_session, :only => [:new, :create, :destroy]
  resource :account, :controller => :users

  resources :password_resets, :only => [:new, :create, :edit, :update]

  mount Sidekiq::Web => '/sidekiq'

end

app/models/person.rb
# Copyright (C) 2013 Devin Breen
# This file is part of dogtag <https://github.com/chiditarod/dogtag>.
#
# dogtag is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dogtag is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dogtag.  If not, see <http://www.gnu.org/licenses/>.
class Person < ApplicationRecord
  validates :first_name, :last_name, :email, :phone, :zipcode, presence: true
  validates :email, format: { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :twitter, format: { :with => /\A^@\w+\z/i, :allow_nil => true, :allow_blank => true, :message => 'needs to begin with @ and be one word' }
  validates :zipcode, format: { :with => /\A\d{5}(-\d{4})?\z/, :message => "should be in the form 12345 or 12345-1234" }
  validates :phone, format: { :with => /\A\d{3}-\d{3}-\d{4}\z/, :message => "should be in the form 555-867-5309" }
  validates :experience, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }
  validates_with PersonValidator, :on => :create

  include Wisper.model

  belongs_to :team

  include ActionView::Helpers::NumberHelper
  def phone=(val)
    super(number_to_phone(val, area_code: false, delimiter: '-'))
  end

  def self.registered_for_race(race_id)
    race = Race.find race_id
    race.finalized_teams.inject([]) do |total, reg|
      total.concat(reg.people.reject{ |person| person.email.downcase =~ /unknown/})
    end
  end
end

app/controllers/people_controller.rb
# Copyright (C) 2014 Devin Breen
# This file is part of dogtag <https://github.com/chiditarod/dogtag>.
#
# dogtag is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dogtag is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dogtag.  If not, see <http://www.gnu.org/licenses/>.
class PeopleController < ApplicationController
  before_action :require_user
  load_and_authorize_resource

  def destroy
    @person = Person.find params[:id]
    @person.subscribe(PersonAuditor.new)
    try_to_delete(@person, team_url(id: @person.team.id))
  end

  def update
    @person = Person.includes(:team).find(params[:id])
    @team = @person.team
    @person.subscribe(PersonAuditor.new)
    try_to_update(@person, person_params, team_url(@person.team.id))
  end

  def edit
    @person = Person.includes(:team).find(params[:id])
    @team = @person.team
  end

  def new
    @team = Team.find params[:team_id]
    @person = Person.new
  end

  def create
    return render :status => :bad_request if params[:person].blank?

    @team = Team.find params[:team_id]
    @person = Person.new(person_params)
    @person.subscribe(PersonAuditor.new)
    @person.team = @team

    if @person.save
      flash[:notice] = I18n.t('create_success')
      redirect_to team_url :id => @person.team.id
    else
      flash.now[:error] = [t('create_failed')]
      @person.errors.each do |e|
        flash.now[:error] << {e.attribute.to_sym => e.message}
      end
    end
  end

  private

  def person_params
    params
      .require(:person)
      .permit(:first_name, :last_name, :email, :phone, :twitter, :experience, :zipcode)
  end
end

app/views/people/_form.html.haml
= form_for [@team, @person], :html => {:role => 'form', :class => 'form-horizontal'} do |f|
  .form-group
    .col-xs-4.control-label
      = label_tag :first_name, t('.first_name')
    .col-xs-6
      = f.text_field :first_name, :class => 'form-control'
  .form-group
    .col-xs-4.control-label
      = label_tag :last_name, t('.last_name')
    .col-xs-6
      = f.text_field :last_name, :class => 'form-control'
  .form-group
    .col-xs-4.control-label
      = label_tag :email, t('.email')
    .col-xs-6
      = f.text_field :email, :class => 'form-control'
  .form-group
    .col-xs-4.control-label
      = label_tag :phone, t('.phone')
      %br
      = t('.we_will_sms')
    .col-xs-6
      = f.text_field :phone, :class => 'form-control'
  .form-group
    .col-xs-4.control-label
      = label_tag :zipcode, t('.zip_code')
    .col-xs-6
      = f.text_field :zipcode, :class => 'form-control'
  .form-group
    .col-xs-4.control-label
      = label_tag :experience, t('.experience')
    .col-xs-5
      = f.select :experience, Team::EXPERIENCE_LEVELS.map.with_index { |n,i| [n, i] }, {:prompt => 'Please Select'}, :class => 'form-control'
  .form-group
    .col-xs-4.control-label
      = label_tag :twitter, t('.twitter')
    .col-xs-4
      = f.text_field :twitter, :class => 'form-control'
  .form-group
    .col-xs-offset-4.col-xs-8
      = f.submit t('save'), :class => ['btn', 'btn-default']
      = link_to team_path(@team.id) do
        .btn.btn-default
          = t('back')

app/views/people/_table.html.haml
%table.table
  %thead
    %tr
      %th
      %th= t('name')
      %th= t('email')
      %th= t('cell_phone')
      %th= t('zipcode')
      %th= t('twitter')
  - people.each do |person|
    %tr
      %td
        - if current_user.is_any_of?(:admin, :operator) || race.open_for_registration? || race.in_final_edits_window?
          = link_to(edit_team_person_url :team_id => person.team.id, :id => person.id) do
            %i.fa.fa-edit.fa-2x
        - if current_user.is? :admin
          = button_to t('delete'), team_person_url(:team_id => person.team.id, :id => person.id), :method=>:delete,  :data => { :confirm => 'Are you sure?' }
      %td
        = person.first_name
        = person.last_name
      %td= person.email
      %td= person.phone
      %td= person.zipcode
      %td= person.twitter

app/views/people/create.html.haml
.page-header
  %h1
    = t('.new_person')

.row
  .col-sm-8
    = render 'form'

app/views/people/edit.html.haml
.page-header
  %h1
    = t('.edit_person')

.row
  .col-sm-8
    = render 'form'

app/views/people/new.html.haml
.page-header
  %h1
    = t('.new_person')

.row
  .col-sm-8
    = render 'form'

app/views/people/show.html.haml
.page-header
  %h1
    = t('.edit_team', :race_name => @race.name)

.row
  .col-sm-12
    = render 'form'

app/views/people/update.html.haml
.page-header
  %h1
    = t('.edit_registration')

.row
  .col-sm-12
    = render 'form'