config/routes.rb
Rails.application.routes.draw do

  get 'users/search', to: 'users#search', as: 'search_users'
  get 'teams/search', to: 'teams#search', as: 'search_teams'
  
  root :controller => 'homepages', :action => "index", :as => :home

  resources :teams, :only => [:new, :create, :edit, :update, :index, :show, :destroy] do
    resources :people, :only => [:new, :create, :edit, :update, :destroy]
    resource :questions, :only => [:show, :create]
  end

  resources :races, :only => [:new, :create, :edit, :update, :index, :show, :destroy] do
    get :registrations
    get :export
    resources :requirements, :only => [:new, :create, :edit, :update, :destroy]
  end

  resources :tiers, :only => [:new, :create, :edit, :update, :destroy]

  resources :charges, :only => [:create] do
    post :refund
  end

  resources :users, :only => [:new, :create, :edit, :update, :index, :show, :destroy]
  resource :user_session, :only => [:new, :create, :destroy]
  resource :account, :controller => :users

  resources :password_resets, :only => [:new, :create, :edit, :update]

  mount Sidekiq::Web => '/sidekiq'

end

app/models/race.rb
# Copyright (C) 2013 Devin Breen
# This file is part of dogtag <https://github.com/chiditarod/dogtag>.
#
# dogtag is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dogtag is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dogtag.  If not, see <http://www.gnu.org/licenses/>.
class Race < ApplicationRecord
  validates :name, :max_teams, :people_per_team, presence: true
  validates :race_datetime, :registration_open, :registration_close, :final_edits_close, presence: true
  validates :max_teams, :people_per_team, :numericality => {
    :only_integer => true,
    :greater_than => 0
  }
  validates :classy_campaign_id, :classy_default_goal, numericality: {
    only_integer: true,
    greater_than: 0,
    allow_nil: true
  }
  validates :name, uniqueness: true
  validates_with RaceValidator

  # todo: validate filter_field based on contents of jsonform schema

  scope :past,    -> { where("race_datetime < ?", Time.zone.now) }
  scope :current, -> { where("race_datetime > ?", Time.zone.now) }

  has_many :teams
  MAX_TEAMS_PER_RACE = 4096 # arbitrary number of maximum teams per race.

  # Each race has different registration requirements that needs
  # to be fulfilled before a team is fully registered.
  has_many :requirements

  def question_fields
    return [] unless jsonform.present?
    JSON.parse(jsonform)['schema']['properties'].keys
  rescue => e
    Rails.logger.error "Could not retrieve possible jsonschema filter fields: #{e}"
    []
  end

  def filter_field_array
    return [] if filter_field.nil?
    filter_field.split(',')
  end

  def enabled_requirements
    requirements.select(&:enabled?)
  end

  def finalized_teams
    Team.all_finalized.where(race_id: id)
  end

  def spots_remaining
    max_teams - finalized_teams.size
  end

  def waitlist_count
    return 0 if not_full?
    teams.size - max_teams
  end

  def over?
    race_datetime < Time.zone.now
  end

  def full?
    finalized_teams.size >= max_teams
  end

  def not_full?
    !full?
  end

  def not_yet_open?
    Time.zone.now < registration_open
  end

  def open_for_registration?
    now = Time.zone.now
    return false if now < registration_open
    return false if now > registration_close
    true
  end

  def registration_over?
    registration_close < Time.zone.now
  end

  def in_final_edits_window?
    now = Time.zone.now
    return false if now < registration_close
    return false if now > final_edits_close
    true
  end

  def registerable?
    not_full? && open_for_registration?
  end

  def days_before_close
    t = Time.zone.now
    return false if registration_close < t
    (registration_close - t).ceil
  end

  def stats
    money_raised = teams.reduce(0) do |memo, team|
      memo + team.money_paid_in_cents
    end

    {
      'money_raised' => money_raised
    }
  end
end

app/controllers/races_controller.rb
# Copyright (C) 2013 Devin Breen
# This file is part of dogtag <https://github.com/chiditarod/dogtag>.
#
# dogtag is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dogtag is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dogtag.  If not, see <http://www.gnu.org/licenses/>.
require 'csv'

class RacesController < ApplicationController
  before_action :require_user, :except => [:index, :show]
  load_and_authorize_resource

  def index
    @past_races = Race.past.order('created_at DESC').includes(:teams)
    @current_races = Race.current.order('created_at DESC').includes(:teams)
  end

  def show
    @race = Race.find params[:id]
    if current_user
      @my_race_teams = Team.belonging_to(current_user.id).where(race_id: @race.id)
      if current_user.is_any_of?(:admin, :operator)
        @stats = @race.stats
      end
    end
  end

  alias edit show

  def new
    @race = Race.new
  end

  def registrations
    @race = Race.find params[:race_id]
    @finalized_teams = Team.all_finalized.where(race_id: @race.id).order('updated_at DESC').includes(:people)
    @waitlisted_teams = Team.all_unfinalized.where(race_id: @race.id).order('updated_at DESC').includes(:people)
  end

  def export
    return render :status => :bad_request if params[:race_id].blank?

    race_id = params[:race_id]
    teams = params[:finalized] ? Team.export(race_id, :finalized => true) : Team.export(race_id)
    data = CSV.generate do |csv|
      teams.each { |i| csv << i }
    end
    send_data data, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=race_#{race_id}_export.csv"
  end

  def create
    return render :status => :bad_request if params[:race].blank?

    @race = Race.new(prepare_params(race_params))

    if @race.save
      flash[:notice] = I18n.t('create_success')
      return redirect_to races_path
    else
      flash.now[:error] = [t('create_failed')]
      @race.errors.each do |e|
        flash.now[:error] << {e.attribute.to_sym => e.message}
      end
    end
  end

  def update
    @race = Race.find params[:id]
    try_to_update(@race, prepare_params(race_params), edit_race_url(@race))
  end

  def destroy
    @race = Race.find params[:id]
    try_to_delete(@race, races_path)
  end

  private

  def prepare_params(hash)
    if hash[:filter_field].present?
      hash[:filter_field] = hash[:filter_field].reject{|f| f.empty?}.join(',')
    end
    hash
  end

  def race_params
    params.
      require(:race).
      permit(:name, :max_teams, :people_per_team,
             :race_datetime, :registration_open, :registration_close, :final_edits_close,
             :classy_campaign_id, :classy_default_goal,
             :jsonform, {filter_field: []}
      )
  end
end

app/views/races/_admin_buttons.html.haml
- if current_user && current_user.is_any_of?(:admin, :operator)
  .btn-group
    %button.btn.btn-default.dropdown-toggle{:type => 'button', :'data-toggle' => 'dropdown'}
      %i.fa.fa-save.fa-fw
      = t('.export')
      %span.caret
    %ul.dropdown-menu{:role => 'menu'}
      %li
        = mail_to Person.registered_for_race(race.id).map(&:email).uniq.join(',') do
          %i.fa.fa-envelope.fa-fw
          All Registered Dawgs
      %li.divider
      %li
        = link_to race_export_url(race, :finalized => true) do
          %i.fa.fa-table.fa-fw
          = t('.finalized_teams')
      %li
        = link_to race_export_url(race) do
          %i.fa.fa-table.fa-fw
          = t('.all_teams')

app/views/races/_form.html.haml
.page-header
  %h1
    = t('.manage_race')
    %small= t('mush')

= form_for @race, :html => {:role => 'form', :class => 'form-horizontal'} do |f|
  .form-group
    .col-sm-4.control-label
      = label_tag :name, t('.name')
    .col-sm-4
      = f.text_field :name, :class => 'form-control'

  .form-group
    .col-sm-4.control-label
      = label_tag :registration_open, t('.registration_open')
    .col-sm-8
      = f.datetime_select :registration_open, :include_seconds => true, :class => 'form-control'
      = Time.zone

  .form-group
    .col-sm-4.control-label
      = label_tag :registration_close, t('.registration_close')
    .col-sm-8
      = f.datetime_select :registration_close, :include_seconds => true, :class => 'form-control'
      = Time.zone

  .form-group
    .col-sm-4.control-label
      = label_tag :final_edits_close, t('.final_edits_close')
    .col-sm-8
      = f.datetime_select :final_edits_close, :include_seconds => true, :class => 'form-control'
      = Time.zone

  .form-group
    .col-sm-4.control-label
      = label_tag :race_datetime, t('.race_datetime')
    .col-sm-8
      = f.datetime_select :race_datetime, :class => 'form-control'
      = Time.zone

  .form-group
    .col-sm-4.control-label
      = label_tag :max_teams, t('.max_teams')
    .col-xs-2
      = f.text_field :max_teams, :class => 'form-control'

  .form-group
    .col-sm-4.control-label
      = label_tag :people_per_team, t('.people_per_team')
    .col-xs-2
      = f.text_field :people_per_team, :class => 'form-control'

  .form-group
    .col-sm-4.control-label
      = label_tag :jsonform, t('.jsonform_data')
    .col-sm-8
      = f.text_area :jsonform, :class => 'form-control'

  .form-group
    .col-sm-4.control-label
      = label_tag :filter_field, t('.filter_field')
    .col-sm-8
      = f.select :filter_field, options_for_select(@race.question_fields, @race.filter_field_array), {}, {multiple: true, class: 'form-control'}

  .form-group
    .col-sm-4.control-label
      = label_tag :classy_campaign_id, t('.classy_campaign_id')
    .col-xs-2
      = f.text_field :classy_campaign_id, :class => 'form-control'

  .form-group
    .col-sm-4.control-label
      = label_tag :classy_default_goal, t('.classy_default_goal')
    .col-xs-2
      = f.text_field :classy_default_goal, :class => 'form-control'

  .form-group
    .col-sm-offset-4.col-sm-8
      = f.submit t('save'), :class => ['btn', 'btn-default']

app/views/races/_new_race_form.html.haml
= form_for @race, :url => {:action => 'create'}, :html => {:role => 'form', :class => 'form-horizontal'} do |f|
  .form-group
    = label_tag :name, t('.name'), :class => ['col-sm-4', 'control-label']
    .col-sm-8
      = f.text_field :name, :class => 'form-control'
  .form-group
    = label_tag :race_datetime, t('.datetime'), :class => ['col-sm-4', 'control-label']
    .col-sm-8
      -#= f.datetime_field :race_datetime, :class => 'form-control'
      = f.datetime_select :race_datetime, :class => 'form-control'
  .form-group
    = label_tag :max_teams, t('.max_teams'), :class => ['col-xs-4', 'control-label']
    .col-xs-2
      = f.text_field :max_teams, :class => 'form-control'
  .form-group
    = label_tag :racers_per_team, t('.racers_per_team'), :class => ['col-xs-4', 'control-label']
    .col-xs-2
      = f.text_field :racers_per_team, :class => 'form-control'
  .form-group
    .col-sm-offset-4.col-sm-8
      = f.submit t('.create'), :class => ['btn', 'btn-default']

app/views/races/_race_form.html.haml
= form_for @race, :html => {:role => 'form', :class => 'form-horizontal'} do |f|
  .form-group
    .col-sm-4.control-label
      = label_tag :name, t('.name')
    .col-sm-8
      = f.text_field :name, :class => 'form-control'
  .form-group
    .col-sm-4.control-label
      = label_tag :race_datetime, t('.race_datetime')
    .col-sm-8
      = f.datetime_select :race_datetime, :class => 'form-control'
  .form-group
    .col-sm-4.control-label
      = label_tag :registration_open, t('.registration_open')
    .col-sm-8
      = f.datetime_select :registration_open, :class => 'form-control'
  .form-group
    .col-sm-4.control-label
      = label_tag :registration_close, t('.registration_close')
    .col-sm-8
      = f.datetime_select :registration_close, :class => 'form-control'
  .form-group
    .col-sm-4.control-label
      = label_tag :max_teams, t('.max_teams')
    .col-xs-2
      = f.text_field :max_teams, :class => 'form-control'
  .form-group
    .col-sm-4.control-label
      = label_tag :people_per_team, t('.people_per_team')
    .col-xs-2
      = f.text_field :people_per_team, :class => 'form-control'
  .form-group
    .col-sm-offset-4.col-sm-8
      = f.submit t('.save'), :class => ['btn', 'btn-default']

app/views/races/_race_item.html.haml
.row
  .col-xs-4.col-sm-3
    .btn
      = link_to race_path(race.id) do
        %i.fa.fa-shopping-cart.fa-4x

    - if race.open_for_registration?
      = link_to new_team_path(:race_id => race.id) do
        - if race.full?
          .btn.btn-warning
            = t('.register_waitlist')
        - else
          .btn.btn-success
            = t('.register_now')

  .col-xs-8.col-sm-9
    %h2
      = link_to race.name, race_path(race)

    - unless terse
      = link_to race_registrations_url(:race_id => race.id) do
        = race.finalized_teams.size
        = t('.teams_registered')

        %br

      - if race.over?
        = t('.race_complete')
      - elsif race.open_for_registration?
        = render 'races/race_metadata', :race => race
      - elsif race.not_yet_open?
        = t('.not_time_yet')
      - else
        = t('.registration_closed')

app/views/races/_race_metadata.html.haml
%p
  - if race.registerable?
    = t('.registration_closes')
    = race.registration_close.strftime("%B %e, %Y, %l:%M:%S %P %Z")

  %br

  - if Time.zone.now < race.registration_open
    = t('.registration_opens')
    = race.registration_open.strftime("%B %e, %Y")
    %br
    = t('.registration_closes')
    = race.registration_close.strftime("%B %e, %Y")

  %br

  = race.spots_remaining
  = t '.spots_remaining'

  - if race.full?
    %h5
      = t('.race_is_full')
    = pluralize(race.waitlist_count, t('.team'))
    = t('.on_waitlist')

app/views/races/create.html.haml
.page-header
  %h1
    = t('.new_race')
    %small= t('mush')

.row
  .col-sm-12
    = render 'race_form'

app/views/races/edit.html.haml
.row
  .col-sm-12
    = render 'form'

.page-header
  %h3
    = t('.race_requirements')
    - if can? :create, @Requirement
      = link_to new_race_requirement_url(@race) do
        %i.fa.fa-plus

- if @race.requirements.blank?
  = t ('.no_requirements_added')
- else
  = render 'requirements/table', :requirements => @race.requirements, :race_id => @race.id

app/views/races/index.html.haml
.page-header
  %h1
    = t('.title')
    - if can? :update, @race
      %small
        = link_to new_race_path do
          %i.fa.fa-plus

- if @current_races.blank?
  = t '.no_races'
- else
  .row.well
    - @current_races.each do |race|
      .col-xs-12.col-md-6.pull-left
        .panelpanel-default
          .panel-body
            = render 'race_item', :race => race, :terse => false
.clearfix

%h3= t('.past_races')
- if @past_races.blank?
  = t '.no_races'
- else
  .row.well
    - @past_races.each do |race|
      .col-xs-12.col-md-6.pull-left
        .panel.panel-default
          .panel-body
            = render 'race_item', :race => race, :terse => true

app/views/races/new.html.haml
.row
  .col-sm-12
    = render 'form'

app/views/races/registrations.html.haml
.panel-group#accordion{:role => "tablist", :'aria-multiselectable' => true}

  %h2
    =t('.registrations_for', name: @race.name)
  %p
    You can sort the columns by clicking the column headers!

  -# completed

  .panel.panel-default.panel-success
    .panel-heading{:role => 'tab', :id => 'headingOne'}
      %h4.panel-title
        %span.fa.fa-smile-o.text-success{:alt => "complete"}
        %a{:'data-toggle' => "collapse", :'data-parent' => "#accordion", :href => "#collapseOne", :'aria-expanded' => 'true', :'aria-controls' => "collapseOne"}
          = t('.finalized_teams')

        .pull-right
          %input.search_finalized{:type => 'search', :'data-column' => "4"}
          %button.reset_finalized{:type => 'button'}
            Reset

        - if @finalized_teams.any? && current_user.is_any_of?(:admin, :operator)
          %small
            = mail_to('dogtag@chiditarod.org', bcc: @finalized_teams.map(&:user).map(&:email).join(',')) do
              %i.fa.fa-envelope
              Email Addresses

    .panel-collapse.collapse.in#collapseOne{:role => "tabpanel", :'aria-labelledby' => "headingOne"}
      .panel-body{:style => "max-height: 600px; overflow-y: scroll;"}
        - if @finalized_teams.any?
          = render 'teams/table', teams: @finalized_teams, table_id: 'finalized', filter_field: @race.filter_field_array
        - else
          = t('.no_finalized_teams')

  -# waitlisted

  .panel.panel-default.panel-warning
    .panel-heading{:role => 'tab', :id => 'headingTwo'}
      %h4.panel-title
        %span.fa.fa-frown-o.text-danger{:alt => "incomplete"}
        %a{:'data-toggle' => "collapse", :'data-parent' => "#accordion", :href => "#collapseTwo", :'aria-expanded' => 'false', :'aria-controls' => "collapseTwo"}
          = t('.waitlisted_teams')

        .pull-right
          %input.search_waitlisted{:type => 'search', :'data-column' => "4"}
          %button.reset_waitlisted{:type => 'button'}
            Reset

        - if @waitlisted_teams.any? && current_user.is_any_of?(:admin, :operator)
          %small
            = mail_to('dogtag@chiditarod.org', bcc: @waitlisted_teams.map(&:user).map(&:email).join(',')) do
              %i.fa.fa-envelope
              Email Addresses

    .panel-collapse.collapse.in#collapseTwo{:role => "tabpanel", :'aria-labelledby' => "headingTwo"}
      .panel-body{:style => "max-height: 600px; overflow-y: scroll;"}
        - if @waitlisted_teams.any?
          = render 'teams/table', :teams => @waitlisted_teams, :table_id => 'waitlisted', filter_field: @race.filter_field_array
        - else
          %h3= t('.no_waitedlisted_teams')

app/views/races/show.html.haml
.row
  .col-sm-12
    .page-header
      .pull-right
        = render 'races/admin_buttons', :race => @race
      %h1
        - if can? :update, @race
          = link_to edit_race_path @race do
            %li.fa.fa-edit
        = @race.name
        %small
          = human_readable @race.race_datetime
      = link_to race_registrations_url(:race_id => @race.id) do
        = @race.finalized_teams.size
        = t('.teams_registered')

.row
  - if @my_race_teams.present?
    .col-sm-12.col-md-6
      %h3= t('.your_teams')
      .row
        - @my_race_teams.each do |team|
          .col-xs-6.pull-left
            = render 'teams/team_item', :team => team, :race => @race

  .col-sm-12.col-md-6
    %h3
      - if @race.not_yet_open?
        = t('.not_time_yet')
      - elsif @race.open_for_registration?
        = @race.finalized_teams.size
        of
        = @race.max_teams
        = t('.teams_registered')
      - else
        = t('.registration_closed')

    = render 'races/race_metadata', :race => @race

    - if @race.open_for_registration?
      - if @race.full?
        = link_to t('.register_waitlist'), new_team_url(:race_id => params[:id]), :class => ['btn', 'btn-warning']
      - else
        = link_to t('.register_now'), new_team_url(:race_id => params[:id]), :class => ['btn', 'btn-success']

  - if can? :update, @race
    .col-sm-12.col-md-6.col-lg-4
      %h3= t('.statistics')
      %dl
        %dd Money Collected
        %dt= price_in_dollars_and_cents(@stats['money_raised'])
      -#= @stats.inspect

app/views/races/update.html.haml
.row
  .col-sm-12
    = render 'form'