config/routes.rb
Rails.application.routes.draw do

  get 'users/search', to: 'users#search', as: 'search_users'
  get 'teams/search', to: 'teams#search', as: 'search_teams'
  
  root :controller => 'homepages', :action => "index", :as => :home

  resources :teams, :only => [:new, :create, :edit, :update, :index, :show, :destroy] do
    resources :people, :only => [:new, :create, :edit, :update, :destroy]
    resource :questions, :only => [:show, :create]
  end

  resources :races, :only => [:new, :create, :edit, :update, :index, :show, :destroy] do
    get :registrations
    get :export
    resources :requirements, :only => [:new, :create, :edit, :update, :destroy]
  end

  resources :tiers, :only => [:new, :create, :edit, :update, :destroy]

  resources :charges, :only => [:create] do
    post :refund
  end

  resources :users, :only => [:new, :create, :edit, :update, :index, :show, :destroy]
  resource :user_session, :only => [:new, :create, :destroy]
  resource :account, :controller => :users

  resources :password_resets, :only => [:new, :create, :edit, :update]

  mount Sidekiq::Web => '/sidekiq'

end

app/models/user.rb
# Copyright (C) 2013 Devin Breen
# This file is part of dogtag <https://github.com/chiditarod/dogtag>.
#
# dogtag is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dogtag is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dogtag.  If not, see <http://www.gnu.org/licenses/>.
class User < ApplicationRecord
  validates :first_name, :last_name, :phone, :email, presence: true
  validates :email, format: { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :email, uniqueness: true

  has_many :completed_requirements
  has_many :teams

  default_scope ->{ order(:last_name) }

  paginates_per 35

  # authlogic
  acts_as_authentic do |c|
    c.login_field = :email
    c.validate_login_field = false
    c.perishable_token_valid_for = 3.hours

    # In version 3.4.0, the default crypto_provider was changed from Sha512 to SCrypt.
    c.transition_from_crypto_providers = [Authlogic::CryptoProviders::Sha512]
    c.crypto_provider = Authlogic::CryptoProviders::SCrypt
  end

  # ---------------------------------------------------------------
  # role_model role support for cancan
  # http://rubydoc.info/gems/role_model/0.8.1/frames

  include RoleModel

  # declare the valid roles -- do not change the order if you
  # add more roles later, always append them at the end.
  roles :admin, :refunder, :operator

  # ---------------------------------------------------------------

  include ActionView::Helpers::NumberHelper
  def phone=(val)
    super(number_to_phone(val, area_code: false, delimiter: '-'))
  end

  def gets_admin_menu?
    (is? :admin) || (is? :operator)
  end

  def fullname
    "#{first_name} #{last_name}"
  end

  def reset_password!(host)
    reset_perishable_token!
    Workers::PasswordResetEmail.perform_async({'user_id' => self.id, 'host' => host})
  end
end

app/controllers/users_controller.rb
# Copyright (C) 2013 Devin Breen
# This file is part of dogtag <https://github.com/chiditarod/dogtag>.
#
# dogtag is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dogtag is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dogtag.  If not, see <http://www.gnu.org/licenses/>.
class UsersController < ApplicationController
  before_action :require_user, except: [:new, :create]
  before_action :set_no_cache, only: %w{search}
  load_and_authorize_resource

  def search
    if params[:q].present?
      query = params[:q]
      @users = User.where('first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ?', "%#{query.parameterize}%", "%#{query.parameterize}%", "%#{query}%")
    else
      @users = User.none
    end

    respond_to do |format|
      format.json { render json: @users.map { |user| { id: user.id, text: "#{user.first_name} #{user.last_name} (#{user.email})" } } }
    end
  end

  def index
    @users = User.page(index_params[:page])
  end

  def show
    @user = User.find(params[:id] || current_user.id)
  end

  def edit
    @user = User.find(params[:id] || current_user.id)
  end

  def new
    @user = User.new
  end

  def create
    return render :status => :bad_request if params[:user].blank?

    @user = User.new user_params

    if @user.save
      # todo: move this to an after_create method in the model
      Workers::WelcomeEmail.perform_async({'user_id' => @user.id})
      flash[:notice] = I18n.t('create_success_user')
      redirect_back_or_default user_url(@user.id)
    else
      flash.now[:error] = [t('create_failed')]
      flash.now[:error] << @user.errors.messages
    end
  end

  def update
    @user = User.find(params[:id])
    try_to_update(@user, user_params, user_url(@user), 'users.update.update_success')
  end

  def destroy
    @user = User.find params[:id]
    try_to_delete(@user, users_path)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone, :password, :password_confirmation, :roles => [])
  end

  def index_params
    params.permit(:page)
  end
end

app/views/users/_form.html.haml
.col-sm-6
  = form_for @user, :html => {:role => 'form', :class => 'form-horizontal'} do |f|
    .form-group
      .col-sm-4.control-label
        = label_tag :name, t('.first_name')
      .col-sm-8
        = f.text_field :first_name, :class => 'form-control'
    .form-group
      .col-sm-4.control-label
        = label_tag :name, t('.last_name')
      .col-sm-8
        = f.text_field :last_name, :class => 'form-control'
    .form-group
      .col-sm-4.control-label
        = label_tag :name, t('.email')
      .col-sm-8
        = f.text_field :email, :class => 'form-control'
    .form-group
      .col-sm-4.control-label
        = label_tag :name, t('.phone')
      .col-sm-8
        = f.text_field :phone, :class => 'form-control'
    .form-group
      .col-sm-4.control-label
        = label_tag :name, t('.password')
      .col-sm-8
        = f.password_field :password, :class => 'form-control'
    .form-group
      .col-sm-4.control-label
        = label_tag :name, t('.password_confirmation')
      .col-sm-8
        = f.password_field :password_confirmation, :class => 'form-control'

    - if current_user && current_user.gets_admin_menu?
      .form-group
        .col-sm-4.control-label
          = label_tag :name, t('.role')
        .col-sm-8
          = f.collection_select :roles, @user.class.valid_roles, :to_s, :to_s,
            {:selected => @user.roles.map(&:to_s), :prompt => ''}, {:multiple => true}

    .form-group
      .col-sm-offset-4.col-sm-8
        = f.submit 'Save', :class => ['btn', 'btn-default']

app/views/users/create.html.haml
%h1= t '.create_user'
%p= t '.instructions'

= render 'form'

app/views/users/edit.html.haml
%h1= t '.update_user'

= render 'form'

app/views/users/index.html.haml
%h1
  = t('.search')

- if current_user.gets_admin_menu? || current_user.is?(:refunder)
  = form_with id: "search-form", url: "#", method: :get, local: true do |f|
    = f.select :user_id, [], {}, class: 'select2-name', data: { placeholder: 'Search by first, last, or email', url: search_users_path }
    = f.hidden_field :id, id: 'selected-user-id'
    = f.select :team_id, [], {}, class: 'select2-team', data: { placeholder: 'Search by team name', url: search_teams_path }
    = f.hidden_field :team_id, id: 'selected-team-id' 

%hr

%h1
  = t('.users')
  %small
    = link_to new_user_path do
      %i.fa.fa-plus

= paginate(@users)

%table#users.table.table-bordered.table-hover
  %thead
    %tr
      %th Name
      %th Team
      %th Race
      - if current_user.is_any_of?([:admin, :refunder])
        %th Activity
      - if current_user.is?(:admin)
        %th Roles
        %th.filter-false Actions

  %tbody
    - @users.each do |user|
      - if user.teams.empty?
        %tr
          %td
            = link_to user.fullname, user
            %br
            %small= mail_to user.email
          %td
          %td
          %td
          - if current_user.is?(:admin)
            %td= user.roles.to_a.map(&:capitalize).join(', ')
            %td
              = link_to 'Edit', edit_user_path(user)
              = link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete
          - else
            %td
            %td
      - else
        - user.teams.each do |t|
          %tr
            %td
              = link_to user.fullname, user
              %br
              %small= mail_to user.email
            %td= link_to t.name, team_url(t.id)
            %td= link_to t.race.name, race_url(t.race.id)
            %td
              %small
                - if current_user.is_any_of?([:admin, :refunder])
                  - t.completed_requirements.each do |cr|
                    .col-xs-4.col-md-4
                      = cr.updated_at.strftime("%b %e, %Y")
                    .col-xs-8.col-md-8
                      - if cr.metadata
                        - cr.metadata.each do |k,v|
                          - if k == 'customer_id'
                            = link_to v, "https://manage.stripe.com/customers/#{v}"
                          - elsif k == 'charge_id'
                            = link_to v, "https://manage.stripe.com/payments/#{v}"
                          - elsif k == 'amount'
                            = price_in_dollars_and_cents(v)
                          %br
                        %br
            - if current_user.is? :admin
              %td= user.roles.to_a.map(&:capitalize).join(', ')
              %td
                = link_to 'Edit', edit_user_path(user)
                = link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete
            - else
              %td
              %td

app/views/users/new.html.haml
%h1= t '.create_user'
%p= t '.instructions'

= render 'form'

app/views/users/show.html.haml
- if can? :update, @user
  = link_to edit_user_path(@user) do
    %i.fa.fa-edit.fa-2x
    = t('edit')

%h3
  %small= t('.name')
  = @user.first_name
  = @user.last_name

%h3
  %small= t('.email')
  = @user.email

%h3
  %small= t('.phone')
  = @user.phone

- if @user.roles.present?
  %h3
    %small= t('.roles')
    = @user.roles.to_a.map(&:capitalize).join(', ')

app/views/users/update.html.haml
%h1= t '.update_user'

= render 'form'