config/routes.rb
Rails.application.routes.draw do

  get 'users/search', to: 'users#search', as: 'search_users'
  get 'teams/search', to: 'teams#search', as: 'search_teams'
  
  root :controller => 'homepages', :action => "index", :as => :home

  resources :teams, :only => [:new, :create, :edit, :update, :index, :show, :destroy] do
    resources :people, :only => [:new, :create, :edit, :update, :destroy]
    resource :questions, :only => [:show, :create]
  end

  resources :races, :only => [:new, :create, :edit, :update, :index, :show, :destroy] do
    get :registrations
    get :export
    resources :requirements, :only => [:new, :create, :edit, :update, :destroy]
  end

  resources :tiers, :only => [:new, :create, :edit, :update, :destroy]

  resources :charges, :only => [:create] do
    post :refund
  end

  resources :users, :only => [:new, :create, :edit, :update, :index, :show, :destroy]
  resource :user_session, :only => [:new, :create, :destroy]
  resource :account, :controller => :users

  resources :password_resets, :only => [:new, :create, :edit, :update]

  mount Sidekiq::Web => '/sidekiq'

end

app/models/race.rb
# Copyright (C) 2013 Devin Breen
# This file is part of dogtag <https://github.com/chiditarod/dogtag>.
#
# dogtag is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dogtag is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dogtag.  If not, see <http://www.gnu.org/licenses/>.
class Race < ApplicationRecord
  validates :name, :max_teams, :people_per_team, presence: true
  validates :race_datetime, :registration_open, :registration_close, :final_edits_close, presence: true
  validates :max_teams, :people_per_team, :numericality => {
    :only_integer => true,
    :greater_than => 0
  }
  validates :classy_campaign_id, :classy_default_goal, numericality: {
    only_integer: true,
    greater_than: 0,
    allow_nil: true
  }
  validates :name, uniqueness: true
  validates_with RaceValidator

  # todo: validate filter_field based on contents of jsonform schema

  scope :past,    -> { where("race_datetime < ?", Time.zone.now) }
  scope :current, -> { where("race_datetime > ?", Time.zone.now) }

  has_many :teams
  MAX_TEAMS_PER_RACE = 4096 # arbitrary number of maximum teams per race.

  # Each race has different registration requirements that needs
  # to be fulfilled before a team is fully registered.
  has_many :requirements

  def question_fields
    return [] unless jsonform.present?
    JSON.parse(jsonform)['schema']['properties'].keys
  rescue => e
    Rails.logger.error "Could not retrieve possible jsonschema filter fields: #{e}"
    []
  end

  def filter_field_array
    return [] if filter_field.nil?
    filter_field.split(',')
  end

  def enabled_requirements
    requirements.select(&:enabled?)
  end

  def finalized_teams
    Team.all_finalized.where(race_id: id)
  end

  def spots_remaining
    max_teams - finalized_teams.size
  end

  def waitlist_count
    return 0 if not_full?
    teams.size - max_teams
  end

  def over?
    race_datetime < Time.zone.now
  end

  def full?
    finalized_teams.size >= max_teams
  end

  def not_full?
    !full?
  end

  def not_yet_open?
    Time.zone.now < registration_open
  end

  def open_for_registration?
    now = Time.zone.now
    return false if now < registration_open
    return false if now > registration_close
    true
  end

  def registration_over?
    registration_close < Time.zone.now
  end

  def in_final_edits_window?
    now = Time.zone.now
    return false if now < registration_close
    return false if now > final_edits_close
    true
  end

  def registerable?
    not_full? && open_for_registration?
  end

  def days_before_close
    t = Time.zone.now
    return false if registration_close < t
    (registration_close - t).ceil
  end

  def stats
    money_raised = teams.reduce(0) do |memo, team|
      memo + team.money_paid_in_cents
    end

    {
      'money_raised' => money_raised
    }
  end
end

app/controllers/application_controller.rb
# Copyright (C) 2013 Devin Breen
# This file is part of dogtag <https://github.com/chiditarod/dogtag>.
#
# dogtag is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dogtag is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dogtag.  If not, see <http://www.gnu.org/licenses/>.
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper :all
  helper_method :current_user_session, :current_user

  # rescue_from ORDERING MATTERS.  Start generic first
  unless Rails.configuration.consider_all_requests_local
    rescue_from Exception, :with => :render_error
    rescue_from ActionController::RoutingError, :with => :render_not_found
    rescue_from CanCan::AccessDenied, :with => :render_access_denied
  end
  # we always want these (including during tests)
  rescue_from ActiveRecord::RecordNotFound, :with => :render_not_found
  rescue_from ActionController::ParameterMissing, :with => :render_400

  def should_run_update_checker
    return false if params['controller'] == 'users' && %w(edit update).include?(params['action'])
    return false if params['controller'] == 'user_sessions' && params['action'] == 'destroy'
    true
  end

  def set_no_cache
    response.headers['Cache-Control'] = 'no-cache, no-store'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = 'Fri, 01 Jan 1990 00:00:00 GMT'
  end

  protected

  def handle_unverified_request
    # raise an exception
    fail ActionController::InvalidAuthenticityToken
    # or destroy session, redirect
    if current_user_session
      current_user_session.destroy
    end
    redirect_to root_url
  end

  private

  def render_not_found(ex)
    log_error(ex)
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end

  def render_400(ex)
    log_error(ex)
    render file: "#{Rails.root}/public/400.html", status: :bad_request
  end

  def render_access_denied(ex)
    log_error(ex)
    redirect_to home_url, :alert => ex.message
  end

  def render_error(ex)
    log_error(ex)
    render file: "#{Rails.root}/public/500.html", status: :internal_server_error
  end

  def log_error(ex)
    Rails.logger.error "#{ex.class} #{ex.message}"
  end

  ## common functions used in controllers ------

  def try_to_update(obj_to_update, attributes_to_apply, redirect_to_url, success_msg='update_success')
    if obj_to_update.update(attributes_to_apply)
      flash[:notice] = I18n.t(success_msg)
      redirect_to(redirect_to_url)
    else
      flash.now[:error] = [I18n.t('update_failed')]
      obj_to_update.errors.each do |e|
        flash.now[:error] << {e.attribute.to_sym => e.message}
      end
    end
  end

  def try_to_delete(obj, redirect_url)
    if obj.destroy
      flash[:notice] = I18n.t('delete_success')
    else
      flash[:error] = I18n.t('destroy_failed')
    end
    redirect_to(redirect_url)
  end

  ## user/session stuff -----------------------------------------

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def require_user
    unless current_user
      store_location
      flash[:notice] = "You must be logged in to access this page"
      redirect_to new_user_session_path
      return false
    end

    user_update_checker
  end

  # if the current_user's User object is invalid, there's been a change in the underlying
  # validation. redirect user to update their info.
  def user_update_checker
    if should_run_update_checker
      user = User.find(current_user.id)
      if user.invalid?
        flash[:notice] = t('users.review_your_info')
        return redirect_to edit_user_url(user)
      end
    end
  end

  def require_no_user
    if current_user
      flash[:notice] = "You must be logged out to access this page"
      redirect_back_or_default account_url
      return false
    end
  end

  def store_location
    session[:return_to] = request.original_url
    #todo: remove this logging once it works
    logger.info "-----------------"
    logger.info session[:return_to]
    logger.info "-----------------"
  end

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end
end

app/helpers/application_helper.rb
# Copyright (C) 2013 Devin Breen
# This file is part of dogtag <https://github.com/chiditarod/dogtag>.
#
# dogtag is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dogtag is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dogtag.  If not, see <http://www.gnu.org/licenses/>.
module ApplicationHelper
end

app/views/application/_flash.html.haml
- flash.each do |key, val|
  .alert{:class => "alert-#{flash_to_bootstrap key}" }
    %button.close{ :data => { :dismiss => "alert" } } x
    - if val.is_a? Array
      - val.each do |msg|
        - if msg.is_a? Hash
          - msg.stringify_keys.each do |k,v|
            - if k.present? && v.present?
              =k.humanize
              =v
              %br
        - else
          %strong= msg
          %br

    - else
      %strong= val

app/views/application/_navbar.html.haml
/ Static navbar
/ view-source:http://getbootstrap.com/examples/navbar-static-top/
.navbar.navbar-default

  .navbar-header
    %button.navbar-toggle{"data-target" => "#navbarColor01", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to(I18n.t('website_title'), home_url, :class => 'navbar-brand')

  .navbar-collapse.collapse#navbarColor01
    %ul.nav.navbar-nav
      %li
        = link_to races_path do
          %i.fa.fa-shopping-cart.fa-2x
          = t('.races')

      - if current_user
        - if current_user.team_ids.present?
          %li
            = link_to teams_path do
              %i.fa.fa-users.fa-2x
              =t '.my_teams'

        - if current_user.gets_admin_menu? || current_user.is?(:refunder)
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              %i.fa.fa-star-o.fa-2x
              =t('admin')
              %b.caret
            %ul.dropdown-menu
              %li.dropdown-header= t '.admin_functions'
              %li= link_to t('search'), users_path
              %li= link_to t('new'), new_user_path
              %li.divider

    %ul.nav.navbar-nav.navbar-right
      - if current_user
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            %i.fa.fa-user.fa-2x
            %b.caret
            %ul.dropdown-menu
              %li.dropdown-header
                = current_user.first_name
                = current_user.last_name
              %li
                = link_to edit_user_path(current_user) do
                  %i.fa.fa-edit.fa-fw
                  =t '.edit_profile'
              %li
                = link_to user_session_path, :method => :delete, :data => {:confirm => 'Are you sure?'} do
                  %i.fa.fa-sign-out.fa-fw
                  =t '.logout'
      - else
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            %i.fa.fa-sign-in.fa-2x
            =t '.login'
            %b.caret
            %ul.dropdown-menu
              %li
                = link_to new_user_session_path do
                  %i.fa.fa-sign-in.fa-fw.fa-2x
                  =t '.login'
              %li
                = link_to new_password_reset_url do
                  %i.fa.fa-paper-plane-o.fa-fw.fa-2x
                  =t '.forgot_password'

        %li
          = link_to new_user_path do
            %i.fa.fa-check-square-o.fa-2x
            =t '.register'

      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
          %i.fa.fa-question-circle.fa-2x
          %b.caret
          %ul.dropdown-menu
            %li.dropdown-header
              =t '.having_problems'
            %li
              = link_to "mailto:dogtag@chiditarod.org?subject=dogtag help" do
                %i.fa.fa-envelope-o.fa-fw
                =t '.email_us'
            %li
              = link_to "https://github.com/chiditarod/dogtag/issues/new" do
                %i.fa.fa-fw.fa-github
                =t '.report_a_bug'

app/views/application/_progressbar.html.haml
.progress
  .progress-bar{:role => 'progressbar', 'style' => "width: #{pct}%", 'aria-valuenow' => pct, 'aria-valuemin' => '0', 'aria-valuemax' => '100'}
    = pct
    &#37;

app/views/application/_sidebar.html.haml
%ul.nav.nav-list
  %li.nav-header
    DogTag
    -#- @service_list.each do |service|
      -#%li= link_to service.service_name, service_path(service.service_name, :page => params[:page])

  -#%li.nav-header
    -#= will_paginate @service_list, :page_links => false